# Generated by Django 2.0.2 on 2018-02-15 19:41

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('offers_private_lessons', models.BooleanField(default=False)),
                ('address', models.TextField()),
                ('bio', models.TextField()),
                ('website', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=20)),
                ('profile_img_url', models.CharField(max_length=256)),
                ('social', django.contrib.postgres.fields.jsonb.JSONField()),
                ('time_created', models.DateTimeField()),
                ('last_modified', models.DateTimeField()),
                ('category', models.ManyToManyField(to='directory.Category')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('time_created', models.DateTimeField()),
                ('last_modified', models.DateTimeField()),
                ('user_type', models.IntegerField(choices=[(1, 'Admin'), (0, 'User')], default=0)),
            ],
        ),
    ]
